version: '3.1'
services:
  shoppingcartapp:
    container_name: shoppingcartcontainer
    image: shoppingcartimage
    build: ./
    ports:
      - '8082:8082'
    depends_on:
      - cartpostgreservice
      - eurekaserver
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8070/eureka
  cartpostgreservice:
    image: postgres
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=shoppingcartdb 
    volumes:
      - ./src/main/resources/sql/cartinit.sql:/docker-entrypoint-initdb.d/cartinit.sql
